In [1]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

In [2]:
df = pd.read_csv('Iris.csv')
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

Dapat kita lihat bahwa terdapat kolom id yang tidak ada hubungan dengan label sehingga kita perlu membuang kolom tersebut. Untuk membuang kolom dari dataframe gunakan fungsi drop().

In [3]:
df = df.drop(columns = 'Id')

Selanjutnya kita perlu melakukan one hot encoding karena label kita merupakan data kategorikal. Fungsi get_dummies() memudahkan kita untuk melakukan hal ini.

In [4]:
category = pd.get_dummies(df.Species)
category

     Iris-setosa  Iris-versicolor  Iris-virginica
0              1                0               0
1              1                0               0
2              1                0               0
3              1                0               0
4              1                0               0
..           ...              ...             ...
145            0                0               1
146            0                0               1
147            0                0               1
148            0                0               1
149            0                0               1

[150 rows x 3 columns]

Kemudian, kita perlu menggabungkan kolom hasil one hot encoding dan membuang kolom spesies karena kolom tersebut tidak akan dipakai.

In [5]:
new_df = pd.concat([df, category], axis = 1)
new_df = new_df.drop(columns='Species')
new_df

,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Iris-setosa,Iris-versicolor,Iris-virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1

Selanjutnya setelah dataframe kita olah, kita konversi dataframe tersebut menjadi numpy array dengan fungsi values dari dataframe.

In [6]:
dataset = new_df.values
dataset

array([[5.1, 3.5, 1.4, ..., 1. , 0. , 0. ],
       [4.9, 3. , 1.4, ..., 1. , 0. , 0. ],
       [4.7, 3.2, 1.3, ..., 1. , 0. , 0. ],
       ...,
       [6.5, 3. , 5.2, ..., 0. , 0. , 1. ],
       [6.2, 3.4, 5.4, ..., 0. , 0. , 1. ],
       [5.9, 3. , 5.1, ..., 0. , 0. , 1. ]])

Nah, tahap berikutnya adalah kita memisahkan antara atribut dan label dengan menjalankan kolom di bawah.

In [7]:
# Pilih 4 kolom pertama untuk dijadikan sebagai atribut
X = dataset[:,0:4]
# Pilih 3 kolom terakhir sebagai label
y = dataset[:,4:7]

Lalu, kita perlu lakukan normalisasi data agar data dapat dipelajari dengan baik oleh jst kita.

In [8]:
# Normalize
min_max_scaler = preprocessing.MinMaxScaler()
X_scale = min_max_scaler.fit_transform(X)
X_scale

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     , 0.06779661, 0.08333333],
       [0.38888889, 0.75      , 0.11864407, 0.08333333],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.08333333, 0.66666667, 0.        , 0.04166667],
       [0.22222222, 0.54166667, 0.11864407, 0.16666667],
       [0.13888889, 0.58333333, 0.15254237, 0.04166667],
       [0.19444444, 0.41666667, 0.10169492, 0.04166667],
       [0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.25      , 0.625     , 0.08474576, 0.04166667],
       [0.25      , 0.58333333, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.13888889, 0.45833333, 0.10169492, 0.04166667],
       [0.30555556, 0.58333333, 0.08474576, 0.125     ],
       [0.25      , 0.875     , 0.08474576, 0.        ],
       [0.33333333, 0.91666667, 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.19444444, 0.5       , 0.03389831, 0.04166667],
       [0.33333333, 0.625     , 0.05084746, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.02777778, 0.41666667, 0.05084746, 0.04166667],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.19444444, 0.625     , 0.05084746, 0.08333333],
       [0.05555556, 0.125     , 0.05084746, 0.08333333],
       [0.02777778, 0.5       , 0.05084746, 0.04166667],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [0.22222222, 0.75      , 0.15254237, 0.125     ],
       [0.13888889, 0.41666667, 0.06779661, 0.08333333],
       [0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.08333333, 0.5       , 0.06779661, 0.04166667],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.75      , 0.5       , 0.62711864, 0.54166667],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.61111111, 0.33333333, 0.61016949, 0.58333333],
       [0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.55555556, 0.54166667, 0.62711864, 0.625     ],
       [0.16666667, 0.16666667, 0.38983051, 0.375     ],
       [0.63888889, 0.375     , 0.61016949, 0.5       ],
       [0.25      , 0.29166667, 0.49152542, 0.54166667],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.44444444, 0.41666667, 0.54237288, 0.58333333],
       [0.47222222, 0.08333333, 0.50847458, 0.375     ],
       [0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.66666667, 0.45833333, 0.57627119, 0.54166667],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.5       , 0.33333333, 0.50847458, 0.5       ],
       [0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.5       , 0.33333333, 0.62711864, 0.45833333],
       [0.58333333, 0.375     , 0.55932203, 0.5       ],
       [0.63888889, 0.41666667, 0.57627119, 0.54166667],
       [0.69444444, 0.33333333, 0.6440678 , 0.54166667],
       [0.66666667, 0.41666667, 0.6779661 , 0.66666667],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.33333333, 0.16666667, 0.47457627, 0.41666667],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.41666667, 0.29166667, 0.49152542, 0.45833333],
       [0.47222222, 0.29166667, 0.69491525, 0.625     ],
       [0.30555556, 0.41666667, 0.59322034, 0.58333333],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.66666667, 0.45833333, 0.62711864, 0.58333333],
       [0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.36111111, 0.41666667, 0.52542373, 0.5       ],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.33333333, 0.25      , 0.57627119, 0.45833333],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.41666667, 0.25      , 0.50847458, 0.45833333],
       [0.19444444, 0.125     , 0.38983051, 0.375     ],
       [0.36111111, 0.29166667, 0.54237288, 0.5       ],
       [0.38888889, 0.41666667, 0.54237288, 0.45833333],
       [0.38888889, 0.375     , 0.54237288, 0.5       ],
       [0.52777778, 0.375     , 0.55932203, 0.5       ],
       [0.22222222, 0.20833333, 0.33898305, 0.41666667],
       [0.38888889, 0.33333333, 0.52542373, 0.5       ],
       [0.55555556, 0.54166667, 0.84745763, 1.        ],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.77777778, 0.41666667, 0.83050847, 0.83333333],
       [0.55555556, 0.375     , 0.77966102, 0.70833333],
       [0.61111111, 0.41666667, 0.81355932, 0.875     ],
       [0.91666667, 0.41666667, 0.94915254, 0.83333333],
       [0.16666667, 0.20833333, 0.59322034, 0.66666667],
       [0.83333333, 0.375     , 0.89830508, 0.70833333],
       [0.66666667, 0.20833333, 0.81355932, 0.70833333],
       [0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.61111111, 0.5       , 0.69491525, 0.79166667],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.38888889, 0.20833333, 0.6779661 , 0.79166667],
       [0.41666667, 0.33333333, 0.69491525, 0.95833333],
       [0.58333333, 0.5       , 0.72881356, 0.91666667],
       [0.61111111, 0.41666667, 0.76271186, 0.70833333],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.94444444, 0.25      , 1.        , 0.91666667],
       [0.47222222, 0.08333333, 0.6779661 , 0.58333333],
       [0.72222222, 0.5       , 0.79661017, 0.91666667],
       [0.36111111, 0.33333333, 0.66101695, 0.79166667],
       [0.94444444, 0.33333333, 0.96610169, 0.79166667],
       [0.55555556, 0.29166667, 0.66101695, 0.70833333],
       [0.66666667, 0.54166667, 0.79661017, 0.83333333],
       [0.80555556, 0.5       , 0.84745763, 0.70833333],
       [0.52777778, 0.33333333, 0.6440678 , 0.70833333],
       [0.5       , 0.41666667, 0.66101695, 0.70833333],
       [0.58333333, 0.33333333, 0.77966102, 0.83333333],
       [0.80555556, 0.41666667, 0.81355932, 0.625     ],
       [0.86111111, 0.33333333, 0.86440678, 0.75      ],
       [1.        , 0.75      , 0.91525424, 0.79166667],
       [0.58333333, 0.33333333, 0.77966102, 0.875     ],
       [0.55555556, 0.33333333, 0.69491525, 0.58333333],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.94444444, 0.41666667, 0.86440678, 0.91666667],
       [0.55555556, 0.58333333, 0.77966102, 0.95833333],
       [0.58333333, 0.45833333, 0.76271186, 0.70833333],
       [0.47222222, 0.41666667, 0.6440678 , 0.70833333],
       [0.72222222, 0.45833333, 0.74576271, 0.83333333],
       [0.66666667, 0.45833333, 0.77966102, 0.95833333],
       [0.72222222, 0.45833333, 0.69491525, 0.91666667],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.69444444, 0.5       , 0.83050847, 0.91666667],
       [0.66666667, 0.54166667, 0.79661017, 1.        ],
       [0.66666667, 0.41666667, 0.71186441, 0.91666667],
       [0.55555556, 0.20833333, 0.6779661 , 0.75      ],
       [0.61111111, 0.41666667, 0.71186441, 0.79166667],
       [0.52777778, 0.58333333, 0.74576271, 0.91666667],
       [0.44444444, 0.41666667, 0.69491525, 0.70833333]])

Lakukan pembagian data menjadi data latih dan data uji. Untuk ukuran data testing yang digunakan 30%. Anda dapat bereksperimen menggunakan nilai lainnya

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scale, y, test_size=0.3)

Untuk arsitektur model kita kali ini menggunakan 3 buah layer. Activation function yang digunakan pada layer terakhir dipilih softmax karena activation tersebut umum dipakai untuk klasifikasi multi kelas seperti ini.

In [10]:
model = Sequential([    
                    Dense(64, activation='relu', input_shape=(4,)),    
                    Dense(64, activation='relu'),    
                    Dense(3, activation='softmax'),])

Lanjutkan dengan menentukan optimizer dan loss function dari model. Untuk masalah klasifikasi multi kelas, Anda dapat menggunakan loss â€˜categorical_crossentropyâ€™.

In [11]:
model.compile(optimizer='Adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

Nah, pada project ini ada sedikit perubahan. Fungsi fit() sekarang kita tampung ke dalam objek hist(history).

In [12]:
hist = model.fit(X_train, Y_train, epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 4ms/step - loss: 1.1050 - accuracy: 0.2000
Epoch 2/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0691 - accuracy: 0.4095
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0349 - accuracy: 0.6857
Epoch 4/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0050 - accuracy: 0.7143
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9752 - accuracy: 0.7048
Epoch 6/100
4/4 [==============================] - 0s 7ms/step - loss: 0.9450 - accuracy: 0.6952
Epoch 7/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9148 - accuracy: 0.6571
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8810 - accuracy: 0.6571
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8470 - accuracy: 0.6571
Epoch 10/100
4/4 [==============================] - 0s 5ms/step - loss: 0.8126 - accuracy: 0.6571
Epoch 11/100
4/4 [==============================] - 0s 4ms/step - loss: 0.7774 - accuracy: 0.6571
Epoch 12/100
4/4 [==============================] - 0s 5ms/step - loss: 0.7403 - accuracy: 0.6571
Epoch 13/100
4/4 [==============================] - 0s 5ms/step - loss: 0.7063 - accuracy: 0.6571
Epoch 14/100
4/4 [==============================] - 0s 4ms/step - loss: 0.6722 - accuracy: 0.6571
Epoch 15/100
4/4 [==============================] - 0s 4ms/step - loss: 0.6394 - accuracy: 0.6571
Epoch 16/100
4/4 [==============================] - 0s 4ms/step - loss: 0.6108 - accuracy: 0.6571
Epoch 17/100
4/4 [==============================] - 0s 4ms/step - loss: 0.5838 - accuracy: 0.6571
Epoch 18/100
4/4 [==============================] - 0s 58ms/step - loss: 0.5607 - accuracy: 0.6571
Epoch 19/100
4/4 [==============================] - 0s 4ms/step - loss: 0.5371 - accuracy: 0.6571
Epoch 20/100
4/4 [==============================] - 0s 4ms/step - loss: 0.5163 - accuracy: 0.6857
Epoch 21/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4992 - accuracy: 0.7429
Epoch 22/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4825 - accuracy: 0.8667
Epoch 23/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4680 - accuracy: 0.9333
Epoch 24/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4540 - accuracy: 0.9143
Epoch 25/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4409 - accuracy: 0.8095
Epoch 26/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4291 - accuracy: 0.8381
Epoch 27/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4166 - accuracy: 0.8952
Epoch 28/100
4/4 [==============================] - 0s 4ms/step - loss: 0.4055 - accuracy: 0.9429
Epoch 29/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3950 - accuracy: 0.9429
Epoch 30/100
4/4 [==============================] - 0s 5ms/step - loss: 0.3846 - accuracy: 0.9619
Epoch 31/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3734 - accuracy: 0.9619
Epoch 32/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3632 - accuracy: 0.9524
Epoch 33/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3530 - accuracy: 0.9619
Epoch 34/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3429 - accuracy: 0.9524
Epoch 35/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3310 - accuracy: 0.9524
Epoch 36/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3196 - accuracy: 0.9524
Epoch 37/100
4/4 [==============================] - 0s 4ms/step - loss: 0.3105 - accuracy: 0.9619
Epoch 38/100
4/4 [==============================] - 0s 5ms/step - loss: 0.2987 - accuracy: 0.9619
Epoch 39/100
4/4 [==============================] - 0s 8ms/step - loss: 0.2913 - accuracy: 0.9429
Epoch 40/100
4/4 [==============================] - 0s 5ms/step - loss: 0.2809 - accuracy: 0.9524
Epoch 41/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2679 - accuracy: 0.9524
Epoch 42/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2582 - accuracy: 0.9524
Epoch 43/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2478 - accuracy: 0.9619
Epoch 44/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2384 - accuracy: 0.9619
Epoch 45/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2297 - accuracy: 0.9619
Epoch 46/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2213 - accuracy: 0.9619
Epoch 47/100
4/4 [==============================] - 0s 4ms/step - loss: 0.2125 - accuracy: 0.9619
Epoch 48/100
4/4 [==============================] - 0s 6ms/step - loss: 0.2045 - accuracy: 0.9619
Epoch 49/100
4/4 [==============================] - 0s 7ms/step - loss: 0.1980 - accuracy: 0.9524
Epoch 50/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1902 - accuracy: 0.9524
Epoch 51/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1837 - accuracy: 0.9619
Epoch 52/100
4/4 [==============================] - 0s 5ms/step - loss: 0.1785 - accuracy: 0.9619
Epoch 53/100
4/4 [==============================] - 0s 5ms/step - loss: 0.1714 - accuracy: 0.9619
Epoch 54/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1672 - accuracy: 0.9619
Epoch 55/100
4/4 [==============================] - 0s 5ms/step - loss: 0.1615 - accuracy: 0.9619
Epoch 56/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1550 - accuracy: 0.9619
Epoch 57/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1500 - accuracy: 0.9619
Epoch 58/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1462 - accuracy: 0.9619
Epoch 59/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1426 - accuracy: 0.9619
Epoch 60/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1373 - accuracy: 0.9619
Epoch 61/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1334 - accuracy: 0.9619
Epoch 62/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1317 - accuracy: 0.9619
Epoch 63/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1253 - accuracy: 0.9619
Epoch 64/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1247 - accuracy: 0.9619
Epoch 65/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1208 - accuracy: 0.9619
Epoch 66/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1179 - accuracy: 0.9619
Epoch 67/100
4/4 [==============================] - 0s 5ms/step - loss: 0.1156 - accuracy: 0.9619
Epoch 68/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1138 - accuracy: 0.9619
Epoch 69/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1109 - accuracy: 0.9619
Epoch 70/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1126 - accuracy: 0.9524
Epoch 71/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1054 - accuracy: 0.9619
Epoch 72/100
4/4 [==============================] - 0s 5ms/step - loss: 0.1041 - accuracy: 0.9619
Epoch 73/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1019 - accuracy: 0.9619
Epoch 74/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1001 - accuracy: 0.9619
Epoch 75/100
4/4 [==============================] - 0s 4ms/step - loss: 0.1065 - accuracy: 0.9619
Epoch 76/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0997 - accuracy: 0.9714
Epoch 77/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0966 - accuracy: 0.9619
Epoch 78/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0959 - accuracy: 0.9619
Epoch 79/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0949 - accuracy: 0.9619
Epoch 80/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0928 - accuracy: 0.9619
Epoch 81/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0891 - accuracy: 0.9619
Epoch 82/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0906 - accuracy: 0.9714
Epoch 83/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0912 - accuracy: 0.9810
Epoch 84/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0870 - accuracy: 0.9714
Epoch 85/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0868 - accuracy: 0.9619
Epoch 86/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0860 - accuracy: 0.9619
Epoch 87/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0831 - accuracy: 0.9619
Epoch 88/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0815 - accuracy: 0.9619
Epoch 89/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0816 - accuracy: 0.9619
Epoch 90/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0839 - accuracy: 0.9810
Epoch 91/100
4/4 [==============================] - 0s 6ms/step - loss: 0.0802 - accuracy: 0.9810
Epoch 92/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0778 - accuracy: 0.9619
Epoch 93/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0782 - accuracy: 0.9619
Epoch 94/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0771 - accuracy: 0.9619
Epoch 95/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0783 - accuracy: 0.9810
Epoch 96/100
4/4 [==============================] - 0s 4ms/step - loss: 0.0747 - accuracy: 0.9810
Epoch 97/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0769 - accuracy: 0.9619
Epoch 98/100
4/4 [==============================] - 0s 6ms/step - loss: 0.0861 - accuracy: 0.9714
Epoch 99/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0781 - accuracy: 0.9619
Epoch 100/100
4/4 [==============================] - 0s 5ms/step - loss: 0.0703 - accuracy: 0.9810

In [13]:
model.evaluate(X_test, Y_test)

2/2 [==============================] - 0s 5ms/step - loss: 0.1373 - accuracy: 0.9556

[0.1373242437839508, 0.9555555582046509]